### ISSUE TITLE
error 404, user not found.

### ISSUE THREAD

**Issue by SBCC144** [OfficeDev/microsoft-teams-apps-company-communicator#1124]
Hello there, could you please advise on how to resolve this issue.

We are experiencing issues with our Company Communicator application. Some users have reported that they are not receiving the Corporate Communications sent through this application.

The accounts affected are active accounts, which are able to send and receive emails and Teams messages without any issues.

Messages are being sent to a distribution list of which these accounts are members.

We have conducted a test by sending a message to a distribution list with only two members: one who is able to successfully receive bot messages and another who cannot.

The status for the message sent shows only one successful delivery, with no status available for the account that did not receive the message.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143484546/76f8d097-aaa9-4c39-a76e-bf857a1f736a)

Both userIDs are in the UserData table in the storage account for the application. 

In the SentNotification table the user experiencing no bot communications shows as error 404, user not found.

The exception shown in this table is: 

Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94

**Comment by SBCC144** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143484546/71cfe337-a58c-40bd-96d7-55840ca70e26)

Many thanks for your assistance on this.

**Comment by gsv022** [comment]
Hi @SBCC144 ,
Thanks for raising the query. Could you please re-upload the author and user app and try mesaging again

**Comment by gsv022** [comment]
@SBCC144 , please let us know the status of the issue.

**Comment by SBCC144** [comment]
@gsv022 Hi, we tried re-uploaded and delivering to both options, unfortunately the same issue still occurs.

**Comment by gsv022** [comment]
Hi @SBCC144 ,
Please share the export results of the latest sent message

**Comment by SBCC144** [comment]
Latest exception from the failing user account, in the SentNotification table shown is:

Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()--- End of stack trace from previous location ---   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94--- End of stack trace from previous location ---   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94

**Comment by gsv022** [comment]
Hi @SBCC144 ,
Please share the export results of the latest sent message

**Comment by SBCC144** [comment]
@gsv022 Hi could you clarify where I would find this please? All I can see for export results for the message is within the author app.  However, as mentioned the user doesn't even appear in this result table, it just states the eight users successful and doesn't show that user. The example below shows one of the eight users, the ninth user doesn't even appear in these results:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143484546/eefc14fa-e31c-46f8-b1d5-3612cf97ff86)

Many thanks

**Comment by gsv022** [comment]
Hi @SBCC144 ,
.
- We want to look into the export results. Here is the reference
<img width="575" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/2f9db13c-fe87-4b80-a265-6169063ba792">

- please share the exported results

**Comment by SBCC144** [comment]
Hi @gsv022, please see below. However, as previously mentioned, the user in question doesn't appear in this list and I can only see the 404 error in the exception table results (posted above). If you look at the highlighted results section, it says "Success: 8, Failure: 0," but there are actually 9 people in this group.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143484546/8a11bdf4-414a-45a1-bdc3-98dba6af0b57)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143484546/815fda16-93ca-4d06-a4d0-b25b43e26d83)

**Comment by gsv022** [comment]
Hi @SBCC144 ,
Please share your mail id(outlook id) so that we can discuss the issue internally.

**Comment by SBCC144** [comment]
Hi @gsv022 it's simeon.benney@cornwall.gov.uk. Thank you

**Comment by gsv022** [comment]
Hi @SBCC144 ,
We have mailed you. Please check and reply

**Comment by gsv022** [comment]
@SBCC144 ,This has been followed up internally.

**Comment by freserovski** [comment]
Hi @gsv022 can you please include also me in emails, we have similar problem with 404 error. freser@gmail.com

**Comment by freserovski** [comment]
Thank you @gsv022 for usable session yesterday. Is it known in which release (if there are any dates known) will be fix included, so workaround with clearing the debatable before each send won't be needed anymore?

**Comment by circeromeromic** [comment]
Hi team, one of my customers is experiencing this same issue. Could you help us get around it ? Thank you!

**Comment by victorsimonlee** [comment]
I don't get why the conversation is taken privately and then results are not shared with the public? Lot's of people reporting the same issue but no public response. This is not appropriate...
