### ISSUE TITLE
The table specified does not exist.

### ISSUE THREAD

**Issue by GBMADemosdmin** [OfficeDev/microsoft-teams-apps-company-communicator#1214]
The only information I found pointing to a real error is bellow, but at the same time the issue i am facing is that the app loads after using the app url not the frontdoor in the app package (in the Entra ID i am using the frontdoor), and no that loads, when I send a message to "all" it is not passing to Drafts, and in the wizard for creating the message it does not display the Teams Groups.

Microsoft.Azure.Cosmos.Table.StorageException: Not Found
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Repositories.BaseRepository`1.ExecuteQueryAsync(TableQuery`1 query, Nullable`1 count, CancellationToken ct) in C:\home\site\repository\Source\CompanyCommunicator.Common\Repositories\BaseRepository.cs:line 0
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Repositories.BaseRepository`1.GetWithFilterAsync(String filter, String partition) in C:\home\site\repository\Source\CompanyCommunicator.Common\Repositories\BaseRepository.cs:line 0
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Repositories.NotificationData.NotificationDataRepository.GetAllPendingScheduledNotificationsAsync() in C:\home\site\repository\Source\CompanyCommunicator.Common\Repositories\NotificationData\NotificationDataRepository.cs:line 269
   at Microsoft.Teams.Apps.CompanyCommunicator.Send.Func.ScheduleSendFunction.Run(TimerInfo myTimer, ILogger log) in C:\home\site\repository\Source\CompanyCommunicator.Send.Func\ScheduleSendFunction.cs:line 66
Request Information
RequestID:e8bab17b-a002-0069-3565-165408000000
RequestDate:Mon, 13 Nov 2023 19:15:00 GMT
StatusMessage:Not Found
ErrorCode:
ErrorMessage:The table specified does not exist.
RequestId:e8bab17b-a002-0069-3565-165408000000
Time:2023-11-13T19:15:00.0325187Z

**Comment by gsv022** [comment]
Hi @GBMADemosdmin ,
Thanks for raising the query. We will check the logs.
As mentioned "_when I send a message to "all" it is not passing to Drafts, and in the wizard for creating the message it does not display the Teams Groups._"
Please share a screenshot showcasing the error while dealing above situations

**Comment by GBMADemosdmin** [comment]
Good of course, let me share some info about the issue and implementation:

Our implementation is version 5.5; the "main"
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150464079/54e5099f-f59f-437d-a42d-c31af4631f62)

and about the error in looking for groups:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150464079/3e03d633-bb51-4709-9db8-e04e593e1923)

and I have tried to send mora than 10 messages but no one got to Drafts (Borradores - Spanish)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150464079/34ebe539-6853-4075-8dab-24b6e40f21c4)

**Comment by gsv022** [comment]
Hi @GBMADemosdmin ,
Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue.

**Comment by GBMADemosdmin** [comment]
Alrady installed in all Teams and enforced install to all clients by policy
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150464079/9189dae8-e3f9-4fd0-bcd2-92d0e000e0ee)

**Comment by gsv022** [comment]
Hi @GBMADemosdmin ,
If it is already added to a specific team,  please try opening the teams in browser and check the observation.
