### ISSUE TITLE
Error when trying to sync with new version 5.5

### ISSUE THREAD

**Issue by Axael85** [OfficeDev/microsoft-teams-apps-company-communicator#1236]
Hello Team,

I'm having some issues when trying to sync application for the version 5.5. I have updated recently with the 5.5 migration guide but the sync fails with the next error code:

**HotFix for app service authentication issue (1}#1226)**

<img width="596" alt="logserror" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/9c4d6f53-7101-4263-a3af-5d0f403b5567">

Attached is the error. 

_**Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Failed to compile.

TS7006: Parameter 'c' implicitly has an 'any' type.
    207 |     setAllUsersState(false);
    208 |     if (teams && teams.length > 0) {
  > 209 |       const teamsSelected = teams.filter((c) => messageState.teams.some((s) => s === c.id));
        |                                           ^
    210 |       setTeamsSelectedOptions(teamsSelected || []);
    211 |       const roastersSelected = teams.filter((c) => messageState.rosters.some((s) => s === c.id));
    212 |       setRostersSelectedOptions(roastersSelected || []);

Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock**_

**Comment by gsv022** [comment]
Hi @Axael85 ,
Thanks for raising the query. Could you please confirm on the below points.

- What is the version of the app before SYNC?
- What is the existing app service plan? Here is the reference.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/11231991-ec20-4795-9d27-5b60622db830">

**Comment by Axael85** [comment]
Hello @gsv022 ,

Thanks for contacting me, the version were the app was on 5.0 and followed the migration guide for the 5.5.
HEre is screenshot for the plan 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/e07d04ab-0267-489c-83df-cf7a3052b64f)

**Comment by Axael85** [comment]
HEllo @gsv022 ,

I have checked the function apps and are pointing to runtime version ~4 and app service to .Net 6

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/20cb71d3-735c-4300-b445-9f3481b571ee)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/5d247b4e-6f62-4c71-8449-187695050cef)

As well tried another sync and same result : 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/a50fdc56-2f56-4e56-8624-1322f1195a09)

**Comment by gsv022** [comment]
Hi @Axael85 ,

- If your previous version is v5.4.1 or lower, please add the parameters as per this [step](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) in the app service configuration. 

- Save it
- Disconnect the repository. Give some time to delete.
- Then connect to the same repository again. 

Keep us posted

**Comment by Axael85** [comment]
Hello @gsv022 ,

As mention befeore, the previous version was 5.0 and then updated to 5.5 following the migration documentation provided. I have double checked the parameters and they were created on the migration documentation steps. 
As well tried to disconect the repository and connect again and now received next error :

Failed to set up deployment: Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: Could not find a part of the path 'C:\home\site\deployments\settings.xml'.     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at XmlSettings.XmlUtility.CreateDocument(XName rootName, String path)
   at XmlSettings.XmlUtility.GetDocument(XName rootName, String path, Boolean createIfNotExists)
   at XmlSettings.Settings.GetDocument(Boolean createIfNotExists)
   at XmlSettings.Settings.SetValueInternal(String section, String key, String value)
   at XmlSettings.Settings.SetValue(String section, String key, String value)
   at Kudu.Core.Settings.DeploymentSettingsManager.SetValue(String key, String value) in C:\Kudu Files\Private\src\master\Kudu.Core\Settings\DeploymentSettingsManager.cs:line 93
   at Kudu.Services.Settings.SettingsController.<>c__DisplayClass4_0.<Set>b__0() in C:\Kudu Files\Private\src\master\Kudu.Services\Settings\SettingsController.cs:line 62
   at Kudu.Contracts.Infrastructure.LockExtensions.<>c__DisplayClass3_0`1.<LockOperation>b__0() in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 59
   at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 34
   at Kudu.Contracts.Infrastructure.LockExtensions.LockOperation[T](IOperationLock lockObj, Func`1 operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 59
   at Kudu.Services.Settings.SettingsController.Set(JObject newSettings) in C:\Kudu Files\Private\src\master\Kudu.Services\Settings\SettingsController.cs:line 0
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Utilities\WebRequestHelper.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 741
   --- End of inner exception stack trace ---
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\ExternalSiteRepositoryProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass370_1.<<UpdateSiteSourceControl>b__1>d.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Controllers\WebCloudController.cs:line 11079
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)
   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl) in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Controllers\WebCloudController.cs:line 11074

**Comment by Axael85** [comment]
Hello @gsv022 ,

Now we are able to sync succesfully, working now! 
Thanks a lot for your support, we can close this case:)

**Comment by gsv022** [comment]
Hi @Axael85 ,
Thank you for the confirmation.
