### ISSUE TITLE
Create new message can not save as drafts.

### ISSUE THREAD

**Issue by reterfreeman** [OfficeDev/microsoft-teams-apps-company-communicator#1242]
Hi, my CC is 5.5 and I used to send messages successfully, but today I can send a message, when I create a new message, select the target (M365 Group), and then save it as a draft, but I can't see anything in the author console, nor can I see any of the messages I used to send.
I tried restarting the application service and still can't save drafts, and it got worse for can't search any groups.

Any ideas on how to do this?

<img width="740" alt="2023-11-30_114756" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151904936/368ab4fc-0f17-4dc6-b143-81f6be14b52f">

**Comment by reterfreeman** [comment]
Update:
<img width="1128" alt="2023-11-30_120620" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151904936/c4173e39-b172-4c0f-b7a6-a1d039b91e63">
<img width="1128" alt="2023-11-30_120706" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151904936/bf724ab8-269f-4f89-99ba-95153fb5a5e3">

**Comment by gsv022** [comment]
Hi @reterfreeman ,
Thanks for raising the query. Please give us sometime we will get back to you soon

**Comment by reterfreeman** [comment]
> Hi @reterfreeman , Thanks for raising the query. Please give us sometime we will get back to you soon

@gsv022 Thanks, I checked the status of the Deployment Center today and it went to "Failed", I think this could be the cause, please advise me, thanks.src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151904936/220d4c9f-5f1c-44aa-a1f8-ea0d2dd42401">

**Comment by reterfreeman** [comment]
@gsv022 I try disconnect and re-connect again, but show error......OMG
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151904936/517162ac-1a38-44ca-8578-618f00c8db3e)
Failed to set up deployment: Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The 'Updating deployment setting' operation conflicts with the pending 'Deleting repository' operation started at 2023-12-01T01:52:40.8335102Z.  Please retry operation later. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Utilities\WebRequestHelper.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 741
   --- End of inner exception stack trace ---
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\ExternalSiteRepositoryProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass369_1.<<UpdateSiteSourceControl>b__1>d.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Controllers\WebCloudController.cs:line 11603
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)
   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl) in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Controllers\WebCloudController.cs:line 11598.

**Comment by gsv022** [comment]
@reterfreeman ,Please give sometime once after disconnecting the repository. Then connect again. It will sync without any issue.

**Comment by gsv022** [comment]
Please share the application insight logs. Here is the reference.
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat. Even the screenshots would be more helpful. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/4747b16e-067a-47ad-a764-ae38a5f67a89)

**Comment by gsv022** [comment]
Please click on that under suggestion- Key based authentication is not permitted on this storage account. If there is any call stack, please share it and even supporting screenshot of the page will be helpful

**Comment by reterfreeman** [comment]
@gsv022 Yes, please.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151904936/44ddffb2-79cc-47dc-94a8-afdae7993bf3)

**Comment by reterfreeman** [comment]
@gsv022 Hi, I have fixed, I enable the storage account key access option, and it's work!
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151904936/0b780660-1235-4b27-9e7b-3729b640b39b)
