### ISSUE TITLE
Communicator message failed delivery to few users

### ISSUE THREAD

**Issue by win-lobo** [OfficeDev/microsoft-teams-apps-company-communicator#1294]
Hi, we are having an issue with a few users as mentioned in the title.

The error message is the following:

`403:Failed`

``Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94``
   
 We used the following sending option:
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/33344125/fdfa3286-1792-4485-ad16-1493d9b6d02d)

The message failed for 6 users, wherein 5 had the same error as above. One of them is having the error: `-2 : App Not Installed`

We have checked with one of those 5 users and they were able to receive the message before at some point, and that the chat app is not blocked on their side.
<img width="206" alt="image005" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/33344125/e732fa6a-4c3c-443d-a88b-39e633d0f9a2">

Coud you please help us resolve this error from a generic approach? 
1. Fix the issue with 403:Failed result.
2. Reinstall the app for the 1 user who has it not installed.

I have seen other similar issues here, but none of them are provided with an specific resolution that I can use in our case. Your help will be much appreciated.

**Comment by gsv022** [comment]
Hi @win-lobo ,
Thanks for raising the query. Please uninstall the user app and re-install it. Then try to send the message again.

**Comment by win-lobo** [comment]
We will try that and let you know the result. A question, uninstalling the user app does delete the previous messages from their chat?
