### ISSUE TITLE
NullReferenceException in MSGraphScopeHandler in App Service after upgrade from v4 to v5

### ISSUE THREAD

**Issue by sergiodminguez** [OfficeDev/microsoft-teams-apps-company-communicator#1312]
After upgrading the application from v4 to v5 following the [wiki](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5), the application is making a request to an endpoint and response code is 500 (Internal Server Error). 

Upon inspecting the logs, the following error is identified:
```plaintext
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Teams.Apps.CompanyCommunicator.Authentication.MSGraphScopeHandler.HasScopesAsync(String[] scopes) in C:\home\site\repository\Source\CompanyCommunicator\Authentication\MSGraphScopeHandler.cs:line 54
   at Microsoft.Teams.Apps.CompanyCommunicator.Authentication.MSGraphScopeHandler.HandleRequirementAsync(AuthorizationHandlerContext context, MSGraphScopeRequirement requirement) in C:\home\site\repository\Source\CompanyCommunicator\Authentication\MSGraphScopeHandler.cs:line 39
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthorizeAsync(AuthorizationPolicy policy, AuthenticateResult authenticationResult, HttpContext context, Object resource)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

It appears that an attribute is missing or there is a failure in the login process utilized by the library. The issue is specifically located in the MSGraphScopeHandler file at line 39.
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/40d2c51b78d6aec8ec1c9d956a93551f717ae347/Source/CompanyCommunicator/Authentication/MSGraphScopeHandler.cs#L39

Which environment variable is missing or how can we solve the exception?

**Comment by gsv022** [comment]
Hi @sergiodminguez ,
Thanks for raising the query.  

- Are you able to access the application? Please share the screenshot for better troubleshooting.
- Have you followed this [migration steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#1-update-the-net-version-of-azure-functions-and-app-service-to-support-net-60-), share the screenshot of the function run time version and .NET version in app service.

**Comment by sergiodminguez** [comment]
Hi @gsv022,

- When we open the form to create a new message, the author App displays the following message on the screen:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/c0ed858a-1937-4567-96a6-1d5ea5f908e6)

- I share screenshots of the app resources:
_App service:_
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/75b19b2c-265e-4898-a12b-e89c13da1ef6)
_Function Apps *-prep-function:_
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/3a5cd23b-c100-4090-8464-b05b131d4ec6)
_Function Apps *-function:_
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/8e87feac-86fe-41be-b7d5-98e8f282cfe1)
_Function Apps *-data-function:_
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/e030c91b-3017-4500-bc73-3168a8ce2752)

**Comment by gsv022** [comment]
Please cross verify if all the parameters mentioned in the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) are added to the app service configuration section or not.

**Comment by sergiodminguez** [comment]
Verified. I attach screenshots for these parameters

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/3e554124-7d80-4697-9d58-7171300a2221)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/056616ac-0a0e-4a26-8fbf-06dc1e202046)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/7bffd8b5-4cf7-4cba-935a-6a0ed50f8910)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11646706/ac5877bf-bf0e-4e20-ab09-4f6a683ec11f)

**Comment by gsv022** [comment]
What is the current app service plan used here. This can be checked in app service overview page.

**Comment by sergiodminguez** [comment]
S2

**Comment by gsv022** [comment]
Hi @sergiodminguez ,
Have you performed sync after adding the parameters or before adding the parameters to app service configuration.

**Comment by sergiodminguez** [comment]
Yes

**Comment by sergiodminguez** [comment]
I did both, at first we did it before, but since it didn't work we put it after too

**Comment by gsv022** [comment]
@sergiodminguez , Could you please check whether cleanup process has been performed for author app as per the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#3-clean-the-company-communicator-v4-author-app-registration)

**Comment by sergiodminguez** [comment]
We did it in the past, and we just did it now and the exception persists. Can you offer more help based on the exception that we attached in the first comment? Thanks.

**Comment by gsv022** [comment]
Please share your mail id so that we can discuss the issue internally.

**Comment by sergiodminguez** [comment]
> Please share your mail id so that we can discuss the issue internally.

I tried to contact you without success, contact me at this email sd8198676@gmail.com
