### ISSUE TITLE
Three Function Apps are reporting an error after updating from 5.0.1 to 5.5.1.

### ISSUE THREAD

**Issue by StanleyLl0yd** [OfficeDev/microsoft-teams-apps-company-communicator#1357]
AZFD0005
Error building configuration in an external startup class.
Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error building configuration in an external startup class. ---> Microsoft.Azure.WebJobs.Script.HostInitializationException : One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions.
 ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=***' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later.
 
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.ValidateExtensionRequirements(List`1 startupTypes) at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 336
 at async Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 222
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__10_0() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 53
 at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
 at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)
 at System.Lazy`1.CreateValue()
 at System.Lazy`1.get_Value()
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 68
 at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalConfigurationStartup(IWebJobsConfigurationBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator,WebJobsBuilderContext context,ILoggerFactory loggerFactory) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 362
 at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_3.<AddScriptHostCore>b__8(IWebJobsStartupTypeLocator locator) at /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 258
 End of inner exception

**Comment by StanleyLl0yd** [comment]
![Screenshot 2024-02-29 at 18 01 59](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131160519/07a57894-3fec-4d8a-a551-455e4c81a5b7)
![Screenshot 2024-02-29 at 18 02 37](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131160519/c07fedf4-d34b-4e32-8df8-2b652402a596)
![Screenshot 2024-02-29 at 18 03 14](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131160519/5a42ef85-4f10-483e-b2ec-9af798ba97c1)
![Screenshot 2024-02-29 at 18 03 37](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131160519/8c28ef5e-c846-4f63-9a53-163d4f0c1f1f)
![Screenshot 2024-02-29 at 18 03 51](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131160519/0f3c9310-e6c7-46a3-887e-b9fdd0ba3f98)

**Comment by gsv022** [comment]
Hi @StanleyLl0yd ,
Thanks for raising the query. There might be a chance that sync didn't happen correctly. Please disconnect the repository and give some time then connect it to the repository. Do the same to other function apps. 

Please keep us posted.

**Comment by StanleyLl0yd** [comment]
> Hi @StanleyLl0yd , Thanks for raising the query. There might be a chance that sync didn't happen correctly. Please disconnect the repository and give some time then connect it to the repository. Do the same to other function apps.
> 
> Please keep us posted.

Hi,

I already did it twice

**Comment by gsv022** [comment]
Hi @StanleyLl0yd ,
Could you please perform one more time. If the problem persists share your mail id we can discuss the issue internally.
