### ISSUE TITLE
App published but users don't not receive messages and I can't download log using export log

### ISSUE THREAD

**Issue by MirianaRebeggianiSacmi** [OfficeDev/microsoft-teams-apps-company-communicator#1395]
We have both apps published, Author and User. It seems Author can't send messages correctly but the users never receive them.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/6fd05b6d-6e0f-46c3-a232-97cd8dc9e2bf)

Futhermore, I can't download log file:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/fd56ff46-ee04-4b7a-a844-b8d9eef0b173)

When this method is executed: GET /api/draftnotifications/scheduledDrafts it gives a 401 error response
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/7437e9aa-1fec-49de-bebb-59fdcff6697b)

Is there something we may have done wrong during the deployment? We have followed the guide.

**Comment by gsv022** [comment]
Hi @MirianaRebeggianiSacmi ,
Thank you for raising the query. Could you please verify the graph-app authentication part is correctly done or not. Here is the [reference](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication).

- Check supported account type- Myorg 
- Check API permissions and Grant Admin Consent is given or not.
- Check URL in authentication and expose an API.

**Comment by MirianaRebeggianiSacmi** [comment]
Hi Sai Venkat!
Yes I've checked it:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/701b1d2f-caee-441d-b99b-8f43ea5dbc61)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/c968e914-6919-4aa6-bd51-67d5a319fafe)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/fea229b6-bf3d-44de-83ac-1cc5a7312b53)

**Comment by gsv022** [comment]
Hi @MirianaRebeggianiSacmi ,
Please keep the permissions only which are mentioned in the deployment guide.

**Comment by MirianaRebeggianiSacmi** [comment]
Ok! I've removed "Profile" from permission. Now, I can export results, and I find this error:
System.AggregateException: Failed to acquire token for client credentials. (AADSTS700016: Application with identifier '6944d981-0dd6-4957-99d6-eb23e9694ece' was not found in the directory 'd6d49420-f39b-4df7-a1dc-d59a935871db'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. Trace ID: 3a8dd88d-23b4-4af3-8bd6-6db53a274e00 Correlation ID: e74a6e36-c49d-4435-8939-ffcf7485777a Timestamp: 2024-04-05 09:51:04Z)

But in the Company Communicator doensn't show again the number of recipients:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/804d5f1f-d766-46de-8ba9-981cdad0cb3a)
It shows 0 instead of 5

**Comment by MirianaRebeggianiSacmi** [comment]
The secret are corret, I've make a mistake in the config of "users" registration. I've correct it, but still not working, different message of error:
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
Now I see the correct number of recepients.

**Comment by gsv022** [comment]
Please share your mail id so that we can schedule the call and discuss the issue interally

**Comment by MirianaRebeggianiSacmi** [comment]
My email is miriana.rebeggiani@sacmigroup.com

**Comment by gsv022** [comment]
We are following the issue internally

**Comment by gsv022** [comment]
Thanks for joining the call. Here is the summary.
During the call it is observed that messages are not getting delivered through any of the sending option. First and second options are giving the error as "_Couldn't find any matches_"

- As a part of troubleshooting it is noticed that secret were created newly but their new secret identifiers are not updated in the respective places. So we have updated in the respective places.

- In the teams admin center, upload custom app is disabled. So we enabled it.

- All the basic configuration looks fine.

It takes some time for the changes in admin center to reflect in teams. Give 24hrs of time and then try sending messages. Please keep us posted
