### ISSUE TITLE
Unable to upgrade from v4 to v5 NullReferenceException 

### ISSUE THREAD

**Issue by frisisuas** [OfficeDev/microsoft-teams-apps-company-communicator#1411]
Hi all.
After upgrading the deployment from v4 to v5 following the documentation, the App Service get the next error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Identity.Web.MergedOptions.PrepareAuthorityInstanceForMsal()
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Teams.Apps.CompanyCommunicator.Authentication.MSGraphScopeHandler.HasScopesAsync(String[] scopes) in C:\home\site\repository\Source\CompanyCommunicator\Authentication\MSGraphScopeHandler.cs:line 54
   at Microsoft.Teams.Apps.CompanyCommunicator.Authentication.MSGraphScopeHandler.HandleRequirementAsync(AuthorizationHandlerContext context, MSGraphScopeRequirement requirement) in C:\home\site\repository\Source\CompanyCommunicator\Authentication\MSGraphScopeHandler.cs:line 39
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthorizeAsync(AuthorizationPolicy policy, AuthenticateResult authenticationResult, HttpContext context, Object resource)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/f551a30a-4c06-457f-b22e-f823b15fe2c5)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/68276be0-0714-4538-9daf-03c36cdfa399)

I have been able to "complete" the deployment from the portal but the application does not finish working. The app registrations seem to have all the permissions you indicate in the documentation.

Any idea?

**Comment by gsv022** [comment]
Hi @frisisuas ,
Thanks for raising the query. Could you please confirm on the below points.

- Have you cleared the author app registration which authentication steps? Please share the supporting screenshots.
- Did you create a new app registration -Graph App registration and performed authentication for this app? Please share the supporting screenshots.
- How about **deploy to azure** part ? if performed, what are the resources got failed during that deployment?
- Is Base Resource name kept same as v4 or new name has been kept  during ARM template filling?

**Comment by frisisuas** [comment]
- Have you cleared the author app registration which authentication steps? Please share the supporting screenshots.

step: [Migration to v5 - Clean the Company Communicator v4 author app registration url](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#3-clean-the-company-communicator-v4-author-app-registration)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/aa8b9da9-c16e-4102-9039-0c9494844caf)


- Did you create a new app registration -Graph App registration and performed authentication for this app? Please share the supporting screenshots.

[Migration to v5 - Clean the Company Communicator v4 author app registration, step 3:](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#3-clean-the-company-communicator-v4-author-app-registration)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/dcfdadb0-3ff4-4cad-9460-7a5d329043d0)



- How about deploy to azure part? if performed, what are the resources got failed during that deployment?
custom deployment
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/d5f9ab0a-bff3-44f5-affb-02c71ca84b6b)


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/44c4ae29-c340-4318-8961-f2243640d6d7)



- Is Base Resource name kept same as v4 or new name has been kept during ARM template filling?

I needed to change the source code for naming convention with the costumer demand.

**Comment by frisisuas** [comment]
Reviewing the storage account, I see that it contains information about the application. Is it possible to deploy a clean version and point to the storage account to migrate the data from there?

**Comment by gsv022** [comment]
Hi @frisiuas,
If the deployment fails, that is fine. Please check the status of deployment for the resources such as function, data-function, prep-function, app service individually. Make sure that they are having the status as success(Active).  Follow the migration guide step-by-step. Please keep us posted on this

_Reviewing the storage account, I see that it contains information about the application. Is it possible to deploy a clean version and point to the storage account to migrate the data from there?_
The answer is no, we don't have the steps for migrating old storage account data to the new deployment and not sure of the consequences. We would be of no help here.
