### ISSUE TITLE
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'

### ISSUE THREAD

**Issue by ReivsonLopes** [OfficeDev/microsoft-teams-apps-company-communicator#1498]
I've already searched the other issues for this same error, I've tried everything that's already been suggested, but I still have the same error.

**Version: 5.5.2**

This error was received when trying to send messages.

```
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
```

**Comment by tiwariShiv7** [comment]
Hi @ReivsonLopes, 
Can you please Share the Screenshot of failures ? To Do this,

- Go to resource group-->Resource of type Application Insights-->Under investigate click Failures -> Take a screenshot and paste here

**Comment by ReivsonLopes** [comment]
Hi @tiwariShiv7!

Here is the screenshoot

![image](https://github.com/user-attachments/assets/6aacd49e-8cde-4f57-8f4f-517cfc973106)

**Comment by tiwariShiv7** [comment]
Hi @ReivsonLopes, Thanks for the screenshot. Please confirm the below queries : 
- Have you used Company Communicator earlier or is this a fresh / new deployment case of Company Communicator? 
- Please check the permission policy Teams admin center
     While deploying app globally, permission policy should allow the company communicator bot. 
     To do this, either “Custom apps” section should be “Allow all apps”
     Or if “Custom app” section is “Allow specific apps and block others”, Add Company communicator user bot in the list
     Or if “Customer app” section is “Block specific apps and allow others”, make sure company communicator user bot is not 
     added to the list.
The error indicating that the issue might be due to policies. However please reverify if it meets the [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix) requirements

**Comment by ReivsonLopes** [comment]
Hi @tiwariShiv7!!

It's a fresh / new deployment.

in the documentation it says that permission policy is no longer used, and when going to the permission policies menu, there is
![image](https://github.com/user-attachments/assets/83786fa6-52e4-40bf-bd00-43a90a673396)

![image](https://github.com/user-attachments/assets/d28c7be2-4fa5-478c-8b0f-335f3398ffcd)

![image](https://github.com/user-attachments/assets/1a131ffc-6bed-41e1-8b9e-bb36cffb1abd)

**Comment by tiwariShiv7** [comment]
Hi @ReivsonLopes , Thank you !! Please help us with the deployment center as well. 
Could you please share the repor URL, the branch name and logs for the deployed CC instance. You can find these info by follwing the below steps -
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center
![image](https://github.com/user-attachments/assets/33a3ab93-40d0-4bb0-b24b-f1665c74f6db)

**Comment by ReivsonLopes** [comment]
hi @tiwariShiv7, Here are the prints as requested

![image](https://github.com/user-attachments/assets/65b07fc0-0bb3-45a4-b4b0-e03e26dc82d5)

![image](https://github.com/user-attachments/assets/75ff1793-e5f5-4bd5-a7c1-a3bbd1ab5e47)

**Comment by ReivsonLopes** [comment]
Any other sugestions @tiwariShiv7?

**Comment by tiwariShiv7** [comment]
Can you also please confirm validating this 
- The error indicating that the issue might be due to policies. However please reverify if it meets the [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)requirements

**Comment by ReivsonLopes** [comment]
Hello @tiwariShiv7 

In my front door settings, i don't have the secont routing rule.

![image](https://github.com/user-attachments/assets/36f5793f-e2ff-45a2-99e4-f7fe3a729e36)

Here is the routingRule1 settings.

![image](https://github.com/user-attachments/assets/a2178bd6-8103-419e-a33f-0fa0613e4e59)

should i create a second routing rule?

**Comment by tiwariShiv7** [comment]
Yes You don't need to create Second Routing Rule if it is not there

**Comment by tiwariShiv7** [comment]
@ReivsonLopes Please share you contact details to connect over Teams.

**Comment by ReivsonLopes** [comment]
@tiwariShiv7 my teams account is reivson.lopes@hsbs.com.br

**Comment by tiwariShiv7** [comment]
We have started following this issue internally.

**Comment by CryogenicPotato** [comment]
Same issue here, exactly as OP.
We're on a fresh 5.5.2 install.
For a bunch of recipients the 403 Forbidden error message is returned

![image](https://github.com/user-attachments/assets/cf2d376c-8c30-4701-9213-aae9e633a86e)

It is not clear why it's throwing error only for a bunch of users.

**Comment by v-jaygupta** [comment]
Hello @ReivsonLopes ,

Connected over call to troubleshoot the issue and found the domain and bot id were missing from the user manifest package, asked to update and this fixed the issue. Please let u sknow if we can close this issue.

**Comment by v-jaygupta** [comment]
Closing this issue as no further action required from our side.
