### ISSUE TITLE
Growing number of users not receiving global messages

### ISSUE THREAD

**Issue by bbruenings** [OfficeDev/microsoft-teams-apps-company-communicator#1587]
Hello CC Team,

we are facing an issue for a while not at a customer where a growing number of users are not receiving global messages.

The User App is installed through a App Policy to all the users and they can see the app in the sidebar of teams.

Unfortunately they don't receive the messages. In the message delivery report csv we can see two different error messages:

- -2: App not installed (even tough it is installed through the app policy)
- Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94

As the number of user is growing - it seems like all new users are not getting the app installed correctly through the policy - the issue becomes more critical for the customer.

Any help is highly appreciated.

Thanks and best regards
Bennet

**Comment by v-jaygupta** [comment]
Hello @bbruenings ,
Thank you for logging the issue!
Please allow us some time to gather the necessary insights we will get back to you soon with a proper response.

**Comment by peddivyshnavi** [comment]
Hi @bbruenings 

- Could you please validate the manifest file which are uploaded in teams.

 **while troubleshooting ADO/github issue [1564](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1564)** 

- We observe that you have conducted an internal assessment, during which they moved CC to a private network and utilized private endpoints for access.

- Which is more related to customized version of CC please note that our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version.

**Comment by peddivyshnavi** [comment]
Marking this ticket as closed as this is more related to customized version. please note that our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version.

**Comment by peddivyshnavi** [comment]
@bbruenings 
We have started discussing this issue internally

**Comment by victorsimonlee** [comment]
I am also having the same issue for a long time (2+ years now). If there's a solution, please share.

**Comment by v-milibiswas** [comment]
Hello @bbruenings ,
We would like to inform you that the Company Communicator App Template will officially be retired as of March 31, 2025. While we will no longer provide issue monitoring or implement feature enhancements for this app, you are welcome to continue using the existing codebase in its current form.
As an alternative, we highly recommend exploring Viva Amplify—a comprehensive and feature-rich solution tailored to address your communication needs with enhanced functionality and ongoing support.
Thank you for your understanding and for your valued engagement with the Company Communicator App throughout its journey.
