### ISSUE TITLE
Half of the users in a group cannot receive the message 

### ISSUE THREAD

**Issue by khaledomara83** [OfficeDev/microsoft-teams-apps-company-communicator#1625]
we have an issue with two instances of company communicator that whenver we send to a group half of them are not getting it and we get the error below  for the ones who cannot receive it 

"Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94"

attached the message delivery report

[Message_Delivery.csv](https://github.com/user-attachments/files/18146919/Message_Delivery.csv)

**Comment by v-milibiswas** [comment]
Hello @khaledomara83,
Please check the permission policy Teams admin center
While deploying app globally, permission policy should allow the company communicator bot.
To do this, either “Custom apps” section should be “Allow all apps”
Or if “Custom app” section is “Allow specific apps and block others”, Add Company communicator user bot in the list
Or if “Customer app” section is “Block specific apps and allow others”, make sure company communicator user bot is not added to the list.
After following the above steps if your issue is still not solved. You can share your mail id, so that we can start the conversation internally.

**Comment by khaledomara83** [comment]
Hello,

We have checked the teams permission policy and the app bot is not blocked


Khaled Omara
Cloud Solution Architect
Modern Work
***@***.******@***.***>
Working hours: 9:00 AM to 6:00 PM GMT+2
***@***.***

**Comment by khaledomara83** [comment]
Any update to this ?

**Comment by khaledomara83** [comment]
Please re-open as the issue is still there

**Comment by khaledomara83** [comment]
yes the proactive installation is set to true and the app permission policy doesn`t block the app
