### ISSUE TITLE
Error al envio de mensajes

### ISSUE THREAD

**Issue by maye-vargas** [OfficeDev/microsoft-teams-apps-company-communicator#822]
good day,

Currently I am doing the implementation of the company with a client, I finish the implementation process, the author works well and the client is added correctly, but when I send a communication with the author, they do not send the messages to the team and they do not notify , the processes remain in sent, correct: 0 and error: 0, it returns and the process is tried, but it remains correct: 0 and errors: 1, would you like to validate that it could be an error?

currently disconnect the function and the app service, reconnecting them again, but even changing the git of the function implementation center, I don't solve it, they still don't notify the messages, they never arrive.

Before changing the implementation of the function, I got this error:

System.AggregateException: Failed to acquire token for client credentials. (AADSTS700016: Application with identifier '6857ae5c-416a-4714-bfce-2b08693dd410' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.You may have sent your authentication request to the wrong tenant.
Trace ID: c9d1f58e-93dc-4680-b6dc-054f40f1e100
Correlation ID: 414ed2b7-6464-4721-a0d7-ccd3491bd501
Timestamp: 2022-08-01 20:36:03Z)
 ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS700016: Application with identifier '6857ae5c-416a-4714-bfce-2b08693dd410' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: c9d1f58e-93dc-4680-b6dc-054f40f1e100
Correlation ID: 414ed2b7-6464-4721-a0d7-ccd3491bd501
Timestamp: 2022-08-01 20:36:03Z
 ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Response status code does not indicate success: 400 (BadRequest).
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
ErrorCode: BadRequest
StatusCode: 400
   --- End of inner exception stack trace ---
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T]()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendHttpMessageAsync(IRequestParameters requestParameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.CheckAndAcquireTokenUsingBrokerAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenForClientCommonAsync(String resource, ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, ClientCredential clientCredential)
   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.AcquireTokenAsync(Boolean forceRefresh)
   at Microsoft.Bot.Connector.Authentication.Retry.Run[TResult](Func`1 task, Func`3 retryExceptionHandler)
ErrorCode: unauthorized_client
StatusCode: 400
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Connector.Authentication.Retry.Run[TResult](Func`1 task, Func`3 retryExceptionHandler)
   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.GetTokenAsync(Boolean forceRefresh)
   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.Microsoft.Bot.Connector.Authentication.IAuthenticator.GetTokenAsync(Boolean forceRefresh)
   at Microsoft.Bot.Connector.Authentication.AppCredentials.GetTokenAsync(Boolean forceRefresh)
   at Microsoft.Bot.Connector.Authentication.AppCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Serv

**Comment by gsv022** [comment]
Hi @maye-vargas ,
Please respond to the below queries

- Could you please share the repo url that you are trying to deploy?
- There might be chance that app secrets were incorrectly configured or expired. Please check.

**Comment by maye-vargas** [comment]
Hi @gsv022 ,

La url que tenia anteriormente https://github.com/OfficeDev/microsoft-teams-apps-company-communicator, pero realice cambios a esta url https://github.com/cristianoag/microsoft-teams-apps-company-communicator/wiki/Deployment-Guide

**Comment by gsv022** [comment]
Hi @maye-vargas ,
It conveys that repo URL is not pointing to the official branch. Any reason for changing the repo URL from official repository URL to another repository. We won't be able to assist if you are using customized one.

**Comment by maye-vargas** [comment]
oK, I made the url changes, but I still get an error.

and rebice in flagship apps and this comes out

![image](https://user-images.githubusercontent.com/86726190/183198914-097fb916-ca4a-499c-b452-a163d2e14c6e.png)
