### ISSUE TITLE
A few messages could not be delivered (403)

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#835]
Hello,

I have done a single message broadcast for 740 recipients and 3 of the messages failed.

The information for the given errors is:

* Error Code = 403
* Exception Details:

`Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
`

I had a look in the users profiles in Azure AD and I could not find anything unusual with their profiles. In fact, in a second test (same 740 audience) they have received the messages, and another 1 person didn't.

Can anybody shed some light on what can be the actual cause of the failures, or any insights on how to find more about it?

Thank you in advance!

**Comment by gsv022** [comment]
Hi @victorsimonlee ,

- Could you please share the export results of the sent message with 1 person failed to receive.
- And what is the version of the app that you are using?

**Comment by victorsimonlee** [comment]
Gu @gsv022, thanks for the reply.

the log file is attached, let me know if that helps - _I had to mask the user names/emails._
[CC_SentMessages_log.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/9303694/CC_SentMessages_log.zip)


Also, I am using version 5.1

**Comment by victorsimonlee** [comment]
*bump*

@gsv022 - any news or insights on what could be the issue I reported?

thanks again.

**Comment by v-royavinash** [comment]
@victorsimonlee ,
Sometimes forbidden error is thrown due to the network calls. Say for example we are sending the notification to 100 users and due to network related issue it fails for 1 specific user. The system will re-try for 10 times however if the issue still persists then it will update the status as failed.

Can you please retry to send the message and confirm if the issue is happening for any specific user ? If its fails for same user then it something to do with the user configuration.
